import pandas as pd
df = pd.read_csv("Employeedata.csv")
print(df)
average_salary = df["Salary"].mean()
print(average_salary)
dept_counts = df["Dept"].value_counts()
print(dept_counts )
max_salary = df[df["Salary"]== df["Salary"].max()]
print(max_salary)
min_salary = df[df["Salary"]== df["Salary"].min()]
print(min_salary)
Average_salary_by_Department = df.groupby("Dept")["Salary"].mean()
print(Average_salary_by_Department)
employees_earning_more_than_50000 = df[df["Salary"]>50000]
print(employees_earning_more_than_50000)
gender_counts = df["Gender"].value_counts()
print(gender_counts)
performance = df["Salary"].apply(lambda x: "Excellent" if x>=58000 else "Good" if x>=50000 else "Average")
print(performance)
Total_salary_by_City = df.groupby("City")["Salary"].sum()
print(Total_salary_by_City)
sort_salary = df.sort_values(by= "Salary",ascending= False)
print(sort_salary)
f = open("UpdateEmployeedata.csv","w",newline= '')
f.write("\naverage_salary:\n")
pd.Series([average_salary],name="average_salary").to_csv(f,index= False)
f.write("\ndept_counts:\n")
dept_counts.to_csv(f,index= False)
f.write("\nmax_salary:\n")
max_salary.to_csv(f,index= False)
f.write("\nmin_salary:\n")
min_salary.to_csv(f,index= False)
f.write("\nAverage_salary_by_Department:\n")
Average_salary_by_Department.to_csv(f,index= False)
f.write("\nemployees_earning_more_than_50000:\n")
employees_earning_more_than_50000.to_csv(f,index= False)
f.write("\ngender_counts:\n")
gender_counts.to_csv(f,index= False)
f.write("\nperformance:\n")
performance.to_csv(f,index= False)
f.write("\nTotal_salary_by_City:\n")
Total_salary_by_City.to_csv(f,index= False)
f.write("\nsort_salary:\n")
sort_salary.to_csv(f,index= False)
f.close()
print("all datasets saved in 'UpdateEmployeedata.csv',")
