import pandas as pd
df = pd.read_csv("Productdata.csv")
print(df)
df["Total_revenue"] = df["Price"] * df["Sold"]
print(df[["Productname","Total_revenue"]])
highest_revenue = df[df["Total_revenue"]== df["Total_revenue"].max()]
print(highest_revenue)
Total_Units_Sold = df["Sold"].sum()
print(Total_Units_Sold)
Average_Price_by_Category = df.groupby("Category")["Price"].mean()
print(Average_Price_by_Category)
low_stock = df[df["Stock"]<60]
print(low_stock)
Stock_Remaining = df["Stock"] - df["Sold"]
print(Stock_Remaining)
Products_With_Price_Above_20000 = df[df["Price"]>20000]
print(Products_With_Price_Above_20000)
sort_revenue = df.sort_values(by= "Total_revenue",ascending= False)
print(sort_revenue)
Total_Revenue_by_Category = df.groupby("Category")["Total_revenue"].sum()
print(Total_Revenue_by_Category)
df["Sold_percent"] = (df["Sold"]/df["Stock"])*100
print(df[["Productname","Sold_percent"]])
f = open("UpdateProductdata.csv","w",newline= '')
f.write('\n[[Productname,Total_revenue]]:\n')
df[["Productname","Total_revenue"]].to_csv(f,index= False)
f.write("\nhighest_revenue:\n")
highest_revenue.to_csv(f,index= False)
f.write("\nTotal_Units_Sold:\n")
pd.Series([Total_Units_Sold],name="Total_Units_Sold").to_csv(f,index= False)
f.write("\nAverage_Price_by_Category:\n")
Average_Price_by_Category.to_csv(f,index= False)
f.write("\nlow_stock:\n")
low_stock.to_csv(f,index= False)
f.write("\nStock_Remaining:\n")
Stock_Remaining.to_csv(f,index= False)
f.write("\nProducts_With_Price_Above_20000:\n")
Products_With_Price_Above_20000.to_csv(f,index= False)
f.write("\nsort_revenue:\n")
sort_revenue.to_csv(f,index= False)
f.write("\nTotal_Revenue_by_Category:\n")
Total_Revenue_by_Category.to_csv(f,index= False)
f.write('\n[["Productname","Sold_percent"]]\n')
df[["Productname","Sold_percent"]].to_csv(f,index= False)
f.close()
print("all datasets saved in 'UpdateProductdata.csv',")
