import pandas as pd
df = pd.read_csv("Salesdata.csv")
print(df)
df["Total_price"] = df["Quantity"] * df["Price"]
total_revenue = df["Total_price"].sum()
print(total_revenue)
most_sold_product = df.groupby("Product")["Quantity"].sum().sort_values(ascending= False)
print(most_sold_product)
sales_by_region = df.groupby("Region")["Total_price"].sum()
print(sales_by_region )
avg_order_value = df["Total_price"].mean()
print(avg_order_value)
laptop_sales = df[df["Product"]== "Laptop"]
print(laptop_sales)
quantity_by_product = df.groupby("Product")["Quantity"].sum()
print(quantity_by_product)
highest_revenue_region = sales_by_region.idxmax()
print("Region with Highest Revenue:", highest_revenue_region)
sort_total_price = df.sort_values(by= "Total_price",ascending= False)
print(sort_total_price)
df["Discount"] = df["Total_price"].apply(lambda x: x*0.1 if x>50000 else 0)
print(df[["OrderID","Total_price","Discount"]])
start_date = '2023-01-12'
df["Date"] = df["Date"].str.strip()
end_date = '2023-01-18'
filtered_sales = df[(df['Date'] >= start_date) & (df['Date'] <= end_date)]
print("Sales between dates:\n", filtered_sales)
f = open("UpdateSalesdata.csv","w",newline= '')
f.write("\ntotal_revenue:\n")
pd.Series([total_revenue],name="total_revenue").to_csv(f,index= False)
f.write("\nmost_sold_product:\n")
most_sold_product.to_csv(f,index= False)
f.write("\nsales_by_region:\n")
sales_by_region.to_csv(f,index= False)
f.write("\navg_order_value:\n")
pd.Series([avg_order_value],name="avg_order_value").to_csv(f,index= False)
f.write("\nlaptop_sales:\n")
laptop_sales.to_csv(f,index= False)
f.write("\nquantity_by_product:\n")
quantity_by_product.to_csv(f,index= False)
f.write("\nhighest_revenue_region:\n")
pd.Series([highest_revenue_region],name="highest_revenue_region").to_csv(f,index= False)
f.write("\nsort_total_price:\n")
sort_total_price.to_csv(f,index= False)
f.write('\n[["OrderID","Total_price","Discount"]]:\n')
df[["OrderID","Total_price","Discount"]].to_csv(f,index= False)
f.write("\nfiltered_sales:\n")
filtered_sales.to_csv(f,index= False)
f.close()
print("all datasets saved in 'UpdateSalesdata.csv',")
