import pandas as pd
df = pd.read_csv("Studentdata.csv")
print(df)
average_score =df[["Maths","Science","English"]].mean()
print(average_score)
df['Total'] = df[['Maths', 'Science', 'English']].sum(axis=1)
print(df[['Name', 'Total']])
topper_in_science = df[df["Science"]== df["Science"].max()]
print(topper_in_science)
gender_counts = df["Gender"].value_counts()
print(gender_counts)
average_score_by_gender = df.groupby("Gender")[["Maths","Science","English"]].mean()
print(average_score_by_gender)
high_scores_of_all_subject = df[(df["Maths"]>80) & (df["Science"]>80) & (df["English"]>80)]
print(high_scores_of_all_subject[["Name","Maths","Science","English"]])
df["Result"] = df["Total"].apply(lambda x: "Pass" if x>=180 else "Fail")
print(df[["Name","Total","Result"]])
sort_total_marks = df.sort_values(by= "Total",ascending= False)
print(sort_total_marks )
female_students = df[df["Gender"]== "F"]
print(female_students)
grade_counts = df["Grade"].value_counts()
print(grade_counts)
f = open("UpdateStudentdata.csv","w",newline= '')
f.write("\naverage_score:\n")
average_score.to_csv(f,index= False)
f.write('\n[["Name", "Total"]]:\n')
df[["Name", "Total"]].to_csv(f,index= False)
f.write("\ntopper_in_science:\n")
topper_in_science.to_csv(f,index= False)
f.write("\ngender_counts:\n")
gender_counts.to_csv(f,index= False)
f.write("\naverage_score_by_gender:\n")
average_score_by_gender.to_csv(f,index= False)
f.write('\nhigh_scores_of_all_subject[["Name","Maths","Science","English"]]:\n')
df[["Name","Maths","Science","English"]].to_csv(f,index= False)
f.write('\n[["Result"]]:\n')
df[["Name","Total","Result"]].to_csv(f,index= False)
f.write("\nsort_total_marks:\n")
sort_total_marks.to_csv(f,index= False)
f.write("\nfemale_students:\n")
female_students.to_csv(f,index= False)
f.close()
print("all datasets saved in 'UpdateStudentdata.csv',")
    
